name: boston
system_name: boston_bikeshare
source_url: "https://bluebikes.com/system-data"
aws_sync: true
s3_bucket: s3://hubway-data

file_matcher:
  - "-tripdata"
renamed_columns:
  # Commonized system columns
  ride_id: id
  rideable_type: bike_type
  started_at: start_time
  ended_at: end_time
  start_station_name: start_station_name
  start_station_id: start_station_id
  end_station_name: end_station_name
  end_station_id: end_station_id
  start_lat: start_station_latitude
  start_lng: start_station_longitude
  end_lat: end_station_latitude
  end_lng: end_station_longitude
  member_casual: member_casual


  # Boston pre-March 2023
  starttime: start_time
  stoptime: end_time
  start station id: start_station_id
  start station name: start_station_name
  start station latitude: start_station_latitude
  start station longitude: start_station_longitude
  end station id: end_station_id
  end station name: end_station_name
  end station latitude: end_station_latitude
  end station longitude: end_station_longitude
  bikeid: bike_id
  usertype: membership_type
  birth year: birth_year
  gender: gender
  Gender: gender
  postal code: postal_code

## Odds and ends
  Member type: membership_type
  member_casual: membership_type


final_columns: 
- start_time
- end_time
- start_station_name
- end_station_name
- membership_type
- gender
- birth_year

date_formats:
  - "%Y-%m-%d %H:%M:%S"
  - "%Y-%m-%d %H:%M:%S.%f"
processing_pipeline:
  - rename_columns
  - convert_to_datetime
  - select_final_columns
